# Generated by Django 4.2.5 on 2023-10-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerInfo',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=200)),
                ('public_key', models.FileField(upload_to='public_keys/')),
                ('proof_of_id', models.FileField(upload_to='proofIDs/')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListingInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('typePropety', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=50)),
                ('buyer', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('amenitiy', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('typeContract', models.CharField(max_length=50)),
                ('ownershipDoc', models.FileField(upload_to='Ownership_Docs/')),
                ('identityDoc', models.FileField(upload_to='Identity_Docs/')),
                ('malicious', models.BooleanField(default=False)),
                ('saleContract', models.FileField(upload_to='Sale_Contract/')),
                ('rentalContract_buyer', models.FileField(upload_to='Rental_buyer/')),
                ('rentalContract_seller', models.FileField(upload_to='Rental_seller/')),
            ],
        ),
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=200)),
                ('public_key', models.FileField(upload_to='publicKeys/')),
                ('proof_of_id', models.FileField(upload_to='proofIDs/')),
                ('email', models.CharField(default='strings', max_length=50)),
            ],
        ),
    ]
