# Generated by Django 4.2.5 on 2023-10-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinginfo',
            name='rentalContract_buyer',
            field=models.FileField(null=True, upload_to='Rental_buyer/'),
        ),
        migrations.AlterField(
            model_name='listinginfo',
            name='rentalContract_seller',
            field=models.FileField(null=True, upload_to='Rental_seller/'),
        ),
        migrations.AlterField(
            model_name='listinginfo',
            name='saleContract',
            field=models.FileField(null=True, upload_to='Sale_Contract/'),
        ),
    ]
