# Generated by Django 4.2.5 on 2023-10-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='sellerinfo',
            name='phone',
        ),
    ]
