# Generated by Django 4.2.5 on 2023-10-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_remove_buyerinfo_phone_remove_sellerinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='salt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buyerinfo',
            name='salt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sellerinfo',
            name='salt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
