# Generated by Django 4.2.5 on 2023-10-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_alter_listinginfo_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listinginfo',
            old_name='amenitiy',
            new_name='amenity',
        ),
    ]
