# Generated by Django 4.2.5 on 2023-10-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_delete_listinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('typePropety', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=50)),
                ('buyer', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amenity', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('locality', models.CharField(max_length=50)),
                ('typeContract', models.CharField(max_length=50)),
                ('ownershipDoc', models.FileField(upload_to='Ownership_Docs/')),
                ('identityDoc', models.FileField(upload_to='Identity_Docs/')),
                ('malicious', models.BooleanField(default=False)),
                ('saleContract', models.FileField(blank=True, null=True, upload_to='Sale_Contract/')),
                ('rentalContract_buyer', models.FileField(blank=True, null=True, upload_to='Rental_buyer/')),
                ('rentalContract_seller', models.FileField(blank=True, null=True, upload_to='Rental_seller/')),
            ],
        ),
    ]
