# Generated by Django 4.2.5 on 2023-11-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_listinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinginfo',
            name='buyer_sign',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='listinginfo',
            name='seller_sign',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
