# Generated by Django 4.2.5 on 2023-11-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_listinginfo_buyer_sign_listinginfo_seller_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerinfo',
            name='malicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listinginfo',
            name='payment_log',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sellerinfo',
            name='malicious',
            field=models.BooleanField(default=False),
        ),
    ]
